"""Reproduce the skill catalog from the unmodified JW2_09/JW2_11 archives."""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tools" / "gameplay_parity"))
from inventory_gameplay_matrix import TrcArchive, action_record, unit_record


def generate(install):
    actions = [action_record(r) for r in TrcArchive(install / "Jw2_11.trc").records[:46]]
    units = [unit_record(r) for r in TrcArchive(install / "Jw2_09.trc").records[:170]]
    bindings = [{"unit": u["unit_id"], "name": u["name"], "abilities": u["skill_action_ids"]}
                for u in units if u["skill_action_ids"]]
    result = {"version": 1, "archives": {name: hashlib.sha256((install / name).read_bytes()).hexdigest()
              for name in ("Jw2_09.trc", "Jw2_11.trc")}, "actions": actions, "bindings": bindings}
    lines = ["// Generated by tools/ai/ranker_commander_skills_catalog.py. Do not edit.",
             '#pragma once', '#include "ranker_types.h"', '#include <array>', 'namespace ranker {',
             'struct AiSkillDefinition {',
             '    u32 mode, target_classes, research, minimum_status, health_cost, mana_cost, radius;',
             '    bool present;', '};',
             'inline constexpr std::array<AiSkillDefinition, 46> kAiSkillDefinitions{{']
    keys = ("direction_or_mode", "target_render_class_mask", "owner_requirement", "active_limit",
            "source_health_cost_or_resource_limit", "secondary_cost_or_queued_limit", "radius")
    for a in actions:
        values = [f'{a[k] & 0xffffffff}u' for k in keys]
        lines.append('    {' + ','.join(values) + ',' + ('true' if a['record_size'] > 1 else 'false')
                     + '}, // ' + str(a['action_id']) + ' ' + a['name'])
    lines += ['}};', 'inline constexpr std::array<u32, 170> kAiInitialSkillMasks{{']
    lines += [f'    0x{u["skill_mask"]:08x}u, // {u["unit_id"]:02x} {u["name"]}' for u in units]
    lines += ['}};', '} // namespace ranker', '']
    return result, '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--install', type=Path, default=ROOT.parent / 'RankerOCPV_Win')
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    result, header = generate(args.install)
    outputs = {ROOT / 'include' / 'ranker_ai_skill_catalog.h': header,
               Path(__file__).with_name('commander_skills.json'): json.dumps(result, indent=2, ensure_ascii=False) + '\n'}
    for path, content in outputs.items():
        if args.check:
            if path.read_text(encoding='utf-8') != content:
                raise ValueError(f'stale catalog: {path}')
        else:
            path.write_text(content, encoding='utf-8', newline='\n')
    print(f'{sum(len(b["abilities"]) for b in result["bindings"])} initial bindings, {len(result["actions"])} action definitions')


if __name__ == '__main__':
    main()
