"""Generate the Commander race catalog from the original TRC data and audited bindings.

The first 42 Tyrano actions retain their indices. Other races use the same
economy/army roles where possible; additional production is appended at 42.
No fabricated GreenHall production (the parity fixture's universal producer)
is admitted into an ordinary Elf game.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tools" / "gameplay_parity"))
from inventory_gameplay_matrix import TrcArchive, unit_record, production_order_records

RACES = ("primitive", "elf", "tyrano", "demon")
# Actions 1..11: worker, support, main line, ranged, air, air, heavy,
# transport/support, siege, hero, specialist. Missing entries stay masked.
TRAIN = (
    (0x00, 0x0f, 0x01, 0x03, 0x07, 0x0e, 0x04, 0x08, 0x06, 0x09, 0x05),
    (0x10, 0x13, 0x11, 0x14, 0x16, 0x1a, 0x19, 0x18, 0x15, 0x1b, 0x1c),
    (0x20, 0x21, 0x22, 0x24, 0x25, 0x27, 0x28, 0x29, 0x2a, 0x2c, 0x2e),
    (0x30, 0x31, 0x32, 0x5a, 0x33, 0x34, 0x38, 0x39, 0x35, 0x3a, 0x3e),
)
BUILD = (
    (0x60, 0x62, 0x63, 0x65, 0x68, 0x66, 0x64, 0x67, 0x6b, 0x69),
    (0x70, 0x72, 0x73, 0x74, 0x75, 0x76, 0x77, 0x78, 0x79, 0x7a),
    (0x80, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8a),
    (0x90, 0x92, 0x93, 0x94, 0x95, 0x96, 0x9a, 0x97, 0x98, 0x99),
)
RESEARCH = (
    (0x00, 0x02, 0x01, 0x03, 0x04, 0x08, 0x09, 0x0a, 0x07, 0x06, 0x2b, 0x2c, 0x37),
    (0x0b, 0x10, 0x0c, 0x0d, 0x0e, 0x11, 0x2e, 0x2f, 0x12, 0x13, 0x2b, 0x32, 0x39),
    (0x14, 0x16, 0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x1d, 0x1e, 0x2a, 0x2b, 0x2d, 0x38),
    (0x1f, 0x21, 0x20, 0x23, 0x24, 0x25, 0x26, 0x27, 0x29, 0x22, 0x2b, 0x30, 0x3a),
)


def generate(install):
    parity = ROOT / "tools" / "gameplay_parity"
    units = [unit_record(r) for r in TrcArchive(install / "Jw2_09.trc").records[:170]]
    archive = TrcArchive(install / "Jw2_10.trc")
    orders = None
    for record in archive.records:
        try:
            orders = production_order_records(record)
            break
        except ValueError:
            continue
    if orders is None:
        raise ValueError("original production orders missing")

    def cases(name):
        return [c for b in json.loads((parity / name).read_text(encoding="utf-8"))["batches"] for c in b["cases"]]

    trains = cases("unit_production_batch_manifest.json")
    builds = cases("construction_batch_manifest.json")
    researches = cases("production_order_batch_manifest.json")
    catalog = []
    for tribe, name in enumerate(RACES):
        base = 0x60 + 16 * tribe
        constructed = {c["building_unit_id"] for c in builds if c["builder_unit_id"] == 16 * tribe}
        producers = {c["produced_unit_id"]: c["producer_unit_id"] for c in trains if c["producer_unit_id"] in constructed}
        laboratories = {c["order_id"]: c["source_unit_id"] for c in researches if c["source_unit_id"] in constructed}
        actions = [dict(kind=0, type=0, producer=0, maximum=0) for _ in range(64)]

        def put(index, kind, value):
            if kind == 1:
                producer, maximum = producers[value], 1 if index == 10 else 0
            elif kind == 2:
                producer = 16 * tribe
                maximum = 3 if value in (base, BUILD[tribe][3]) else 6 if value == base + 3 else 24 if value == base + 2 else 1
            else:
                producer, maximum = laboratories[value], orders[value]["max_variant_count"]
            actions[index] = dict(kind=kind, type=value, producer=producer, maximum=maximum)

        for i, value in enumerate(TRAIN[tribe], 1):
            # Keep duplicate role slots unavailable rather than duplicate the
            # probability mass of one action in the categorical distribution.
            if value not in TRAIN[tribe][:i - 1]:
                put(i, 1, value)
        for i, value in enumerate(BUILD[tribe], 12):
            put(i, 2, value)
        for i, value in enumerate(RESEARCH[tribe], 22):
            put(i, 3, value)
        extra = 42
        # Preserve Tyrano's existing action support exactly on migration.
        if tribe != 2:
            for kind, values, used in ((1, producers, TRAIN[tribe]), (2, constructed, BUILD[tribe]), (3, laboratories, RESEARCH[tribe])):
                for value in sorted(set(values) - set(used)):
                    if extra >= 64:
                        raise ValueError("race catalog exceeds macro head")
                    put(extra, kind, value)
                    extra += 1
        catalog.append(dict(tribe=tribe, name=name, actions=actions))

    lines = ["// Generated by tools/ai/ranker_commander_catalog.py; do not edit.",
             "#pragma once", '#include "ranker_types.h"', "#include <array>",
             "namespace ranker {", "struct CommanderRaceAction { u32 kind, type, producer, maximum; };",
             "inline constexpr std::array<std::array<CommanderRaceAction, 64>, 4> kCommanderRaceActions{{"]
    for row in catalog:
        lines.append("    {{ // " + row["name"])
        for i, action in enumerate(row["actions"]):
            lines.append("        {%d,0x%02x,0x%02x,%d}, // %d" % (action["kind"], action["type"], action["producer"], action["maximum"], i))
        lines.append("    }},")
    lines.extend(["}};", "struct CommanderRaceDefinition { u32 cost, population, width, height, interaction_width, interaction_height; };",
                  "inline constexpr std::array<CommanderRaceDefinition, 170> kCommanderRaceDefinitions{{"])
    for u in units:
        lines.append("    {%d,%d,%d,%d,%d,%d}, // 0x%02x %s" % (u["resource_cost"], u["population_cost"], u["footprint_width"], u["footprint_height"], u["interaction_bounds_width"], u["interaction_bounds_height"], u["unit_id"], u["name"]))
    lines.extend(["}};", "} // namespace ranker", ""])
    (ROOT / "include" / "ranker_ai_commander_races.h").write_text("\n".join(lines), encoding="utf-8")
    (ROOT / "tools" / "ai" / "commander_races.json").write_text(json.dumps(catalog, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--install-dir", type=Path, required=True)
    generate(parser.parse_args().install_dir)
