// Generated by tools/ai/ranker_commander_skills_catalog.py. Do not edit.
#pragma once
#include "ranker_types.h"
#include <array>
namespace ranker {
struct AiSkillDefinition {
    u32 mode, target_classes, research, minimum_status, health_cost, mana_cost, radius;
    bool present;
};
inline constexpr std::array<AiSkillDefinition, 46> kAiSkillDefinitions{{
    {3u,29u,1u,0u,0u,100u,0u,true}, // 0 Fall out
    {3u,31u,4294967295u,3u,0u,60u,0u,true}, // 1 Thunder bolt
    {3u,29u,4294967295u,2u,0u,60u,0u,true}, // 2 Shield
    {2u,29u,4294967295u,3u,0u,50u,80u,true}, // 3 Mass temper
    {1u,0u,4294967295u,0u,0u,150u,0u,true}, // 4 Teleport
    {2u,29u,4294967295u,6u,0u,200u,48u,true}, // 5 Jump portal
    {1u,23u,4294967295u,2u,0u,75u,45u,true}, // 6 Drop Stone
    {3u,13u,4294967295u,0u,0u,0u,0u,true}, // 7 Vanishing
    {3u,29u,4294967295u,0u,0u,75u,0u,true}, // 8 Fake
    {2u,31u,18u,0u,0u,0u,64u,true}, // 9 Meteo
    {4u,29u,4294967295u,0u,0u,100u,0u,true}, // 10 Resurrect
    {3u,29u,4294967295u,2u,100u,0u,0u,true}, // 11 Stone curse
    {0u,23u,52u,0u,1u,0u,100u,true}, // 12 Suicide
    {1u,29u,4294967295u,0u,125u,0u,110u,true}, // 13 Noxious gas
    {1u,19u,4294967295u,1u,200u,0u,145u,true}, // 14 Quake
    {1u,0u,4294967295u,0u,120u,0u,0u,true}, // 15 Rise death
    {1u,8u,1u,2u,0u,100u,100u,true}, // 16 Sky Fallout
    {3u,29u,4294967295u,0u,0u,100u,0u,true}, // 17 Blessing
    {0u,0u,4294967295u,0u,200u,0u,0u,true}, // 18 Shadow Force
    {0u,13u,4294967295u,0u,0u,15u,0u,true}, // 19 Hide
    {3u,29u,4294967295u,0u,0u,50u,0u,true}, // 20 Interlace
    {3u,29u,50u,0u,0u,150u,0u,true}, // 21 Exchange
    {1u,1u,4294967295u,0u,0u,200u,55u,true}, // 22 Entangle
    {1u,1u,4294967295u,1u,0u,200u,0u,true}, // 23 Hurdle
    {3u,2u,53u,0u,0u,0u,32u,true}, // 24 Corrupt
    {4u,1u,4294967295u,0u,40u,0u,0u,true}, // 25 Rebirth
    {1u,31u,4294967295u,0u,80u,0u,112u,true}, // 26 Recharge
    {3u,1u,4294967295u,0u,0u,0u,0u,true}, // 27 Absorb
    {4u,13u,52u,0u,150u,0u,0u,true}, // 28 Bonefighter
    {1u,8u,4294967295u,3u,150u,0u,100u,true}, // 29 Airquake
    {0u,0u,0u,0u,0u,0u,0u,false}, // 30 Null.maz
    {0u,5u,4294967295u,0u,0u,0u,0u,true}, // 31 HideOff
    {0u,31u,55u,0u,2u,0u,0u,true}, // 32 Rage
    {0u,31u,57u,0u,1u,0u,0u,true}, // 33 HolyMind
    {0u,31u,56u,0u,1u,0u,0u,true}, // 34 Haste
    {0u,31u,58u,0u,2u,0u,0u,true}, // 35 BloodGuard
    {0u,29u,0u,0u,0u,0u,0u,true}, // 36 AvatarAura
    {2u,23u,54u,0u,0u,0u,180u,true}, // 37 Blasting
    {0u,0u,4294967295u,0u,0u,0u,0u,true}, // 38 Berry_fly
    {0u,0u,4294967295u,0u,0u,0u,0u,true}, // 39 Elf Build
    {3u,29u,4294967295u,0u,0u,2u,0u,true}, // 40 Cure
    {1u,13u,4294967295u,0u,0u,0u,0u,true}, // 41 Egg Mine
    {3u,13u,0u,0u,0u,0u,0u,true}, // 42 Mana Fill
    {0u,21u,0u,0u,0u,0u,0u,true}, // 43 Morale
    {0u,31u,4294967295u,0u,0u,0u,0u,true}, // 44 Bline
    {0u,0u,4294967295u,0u,0u,0u,0u,true}, // 45 Level Up
}};
inline constexpr std::array<u32, 170> kAiInitialSkillMasks{{
    0x00000000u, // 00 BuildMan
    0x00000000u, // 01 PowerMan
    0x00000000u, // 02 Giant
    0x00000000u, // 03 Soldier
    0x00000000u, // 04 Knight
    0x00000000u, // 05 Revolver
    0x00000000u, // 06 BowMachine
    0x00000000u, // 07 Squadron
    0x00000000u, // 08 Flattop
    0x00010001u, // 09 Chief
    0x00000000u, // 0a PowerMan (Shield of Peace)
    0x00000000u, // 0b Soldier (Fire Arrow)
    0x00000000u, // 0c Soldier (Venom Arrow)
    0x00000000u, // 0d Knight (Spear of Justice)
    0x00080000u, // 0e Kalma
    0x00000000u, // 0f Silvan
    0x00000000u, // 10 Wizard
    0x00000002u, // 11 RedElf
    0x0000000cu, // 12 WhiteElf
    0x00000030u, // 13 Ranger
    0x00000040u, // 14 BlueElf
    0x00020000u, // 15 Unicorn
    0x00000100u, // 16 Pixie
    0x00000200u, // 17 ManaSpread
    0x00000000u, // 18 ElfRing
    0x00000000u, // 19 Dragon
    0x00000000u, // 1a phoenix
    0x00000400u, // 1b AngelElf
    0x00c00000u, // 1c GreenElf
    0x00380000u, // 1d DarkElf
    0x00000000u, // 1e Null.chr
    0x00000000u, // 1f Null.chr
    0x00000000u, // 20 Dinos
    0x00000000u, // 21 Masos
    0x00000000u, // 22 Velocis
    0x00000000u, // 23 TwinVelocis
    0x00000000u, // 24 Dilophos
    0x00000000u, // 25 Rhamphos
    0x00000000u, // 26 TwinRhamphos
    0x00000000u, // 27 Pteras
    0x00000000u, // 28 Trices
    0x00000000u, // 29 Dsunguri
    0x00000000u, // 2a EggThrower
    0x00000000u, // 2b Mutant
    0x00000000u, // 2c Tyranos
    0x00000000u, // 2d TwinPteras
    0x00000000u, // 2e Kentros
    0x00000000u, // 2f Null.chr
    0x00000000u, // 30 Insect
    0x00000000u, // 31 Skeleton
    0x00000000u, // 32 MudMan
    0x01000000u, // 33 DeathEye
    0x00040000u, // 34 Phantom
    0x00000000u, // 35 Gargoyle
    0x00000800u, // 36 Kelpa
    0x00006000u, // 37 Warlock
    0x00000000u, // 38 KingDemon
    0x00000000u, // 39 Darkbat
    0x00008000u, // 3a Devil
    0x00000000u, // 3b RiseZombie1
    0x00000000u, // 3c RiseZombie2
    0x00000000u, // 3d Imp
    0x0e000000u, // 3e FemmeFatale
    0x20000000u, // 3f Nightmare
    0x00000000u, // 40 Tyranosaurus
    0x00000000u, // 41 Triceratops
    0x00000000u, // 42 Ceratosaurus
    0x00000000u, // 43 Pachycephalosaurus
    0x00000000u, // 44 Dilophosaurus
    0x00000000u, // 45 Velociraptor
    0x00000000u, // 46 Brachiosaurus
    0x00000000u, // 47 Stegosaurus
    0x00000000u, // 48 Parasaurolophus
    0x00000000u, // 49 Saltasaurus
    0x00000000u, // 4a Protoceratops
    0x00000000u, // 4b Galimimus
    0x00000000u, // 4c Psittacosaurus
    0x00000000u, // 4d Pteranodon
    0x00000000u, // 4e Rhamphorhynchus
    0x00000000u, // 4f Plesiosaurs
    0x00000000u, // 50 Peleneustes
    0x00000000u, // 51 PicaTyrano
    0x00000000u, // 52 82.chr
    0x00000000u, // 53 Alien1
    0x00000000u, // 54 Alien2
    0x00000000u, // 55 Alien3
    0x00000000u, // 56 86.chr
    0x00000000u, // 57 Nashka
    0x00000000u, // 58 88.chr
    0x00000000u, // 59 89.chr
    0x00001000u, // 5a BoneFighter
    0x00000000u, // 5b Silvan_item
    0x00000000u, // 5c SkyBallista
    0x00000000u, // 5d SkyBullet
    0x00000000u, // 5e Giant_item
    0x00000000u, // 5f DoubleBow_item
    0x00000000u, // 60 Sanctuary
    0x00000000u, // 61 Null.chr
    0x00000000u, // 62 House
    0x00000000u, // 63 StoneTower
    0x00000000u, // 64 PowerHouse
    0x00000000u, // 65 SoldierHouse
    0x00000000u, // 66 SkyHouse
    0x00000000u, // 67 Blacksmith
    0x00000000u, // 68 LandIncreaser
    0x00000000u, // 69 SkyIncreaser
    0x00000000u, // 6a Trap
    0x00000000u, // 6b PowerIncreaser
    0x00000000u, // 6c IronIncreaser
    0x00000000u, // 6d Null.chr
    0x00000000u, // 6e Null.chr
    0x00000000u, // 6f SummonHouse
    0x00000000u, // 70 Heaven
    0x00000000u, // 71 Bubble
    0x00000000u, // 72 ElfTree
    0x00000000u, // 73 Bubble
    0x00000000u, // 74 RedHall
    0x00000000u, // 75 BlueHall
    0x00000000u, // 76 ManaHall
    0x00000000u, // 77 SkyHall
    0x00000000u, // 78 ElfLibrary
    0x00000000u, // 79 SkyLibrary
    0x00000000u, // 7a ManaLibrary
    0x00000000u, // 7b GreenHall
    0x00000000u, // 7c HonyTemple
    0x00000000u, // 7d Hurdle
    0x00000000u, // 7e Null.chr
    0x00000000u, // 7f SummonHall
    0x00000000u, // 80 TyranoNest
    0x00000000u, // 81 Null.chr
    0x00000000u, // 82 Nest
    0x00000000u, // 83 Ascomoid
    0x00000000u, // 84 EggNest
    0x00000000u, // 85 LandNest
    0x00000000u, // 86 SkyNest
    0x00000000u, // 87 ThrowNest
    0x00000000u, // 88 UpgradeNest
    0x00000000u, // 89 LandNisdos
    0x00000000u, // 8a SkyNisdos
    0x00000000u, // 8b Null.chr
    0x00000000u, // 8c Null.chr
    0x00000000u, // 8d Null.chr
    0x00000000u, // 8e Null.chr
    0x00000000u, // 8f SummonNest
    0x00000000u, // 90 DemonDen
    0x00000000u, // 91 Null.chr
    0x00000000u, // 92 Tomb
    0x00000000u, // 93 Volcano
    0x00000000u, // 94 DeathDen
    0x00000000u, // 95 FlyPortal
    0x00000000u, // 96 MagicDen
    0x00000000u, // 97 Hell
    0x00000000u, // 98 DirtyPortal
    0x00000000u, // 99 HighPortal
    0x00000000u, // 9a FlyDen
    0x00000000u, // 9b EvilPortal
    0x00000000u, // 9c Null.chr
    0x00000000u, // 9d Null.chr
    0x00000000u, // 9e SummonDen
    0x00000000u, // 9f SummonDen
    0x00000000u, // a0 NoxiousWeed
    0x00000000u, // a1 Poisonous
    0x00000000u, // a2 Treant
    0x00000000u, // a3 DemonFlower
    0x00000000u, // a4 Alien4
    0x00000000u, // a5 165.chr
    0x00000000u, // a6 166.chr
    0x00000000u, // a7 167.chr
    0x00000000u, // a8 168.chr
    0x00000000u, // a9 169.chr
}};
} // namespace ranker
